# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nicole Paquet - Portraitiste
email: nicole.paquet@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nicole Paquet est une artiste et portraitiste québécoise. 
  Voyez quelques-unes de ses plus belles œuvres et tableaux 
  au pastel et à l'acrylique.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicolepaquet.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
lang: fr_CA
facebook_username: nicolepaquetpastel
author: Nicole Paquet

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-menus
  - octopress-paginate
  - jekyll-seo-tag
  - jekyll-archives
permalink: /blogue/:title/
cloudinary_url: "https://res.cloudinary.com/npaquet-pastel/image/upload"


highlighter: rouge

kramdown:
  syntax_highlighter: rouge

collections:
#  category:
#    output: true
#    permalink: /blogue/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      identifier: blog
      layout: post
  -
    scope:
      path: "blogue"
      type: "pages"
    values:
      identifier: blog
      #layout: category
  -
    scope:
      path: "_portfolio" # an empty string here means all files in the project
      type: "portfolio"
    values:
      identifier: portfolio
      layout: single-portfolio


jekyll-archives:
  enabled:
    - tags
    - categories
  layout: 'archives-index'
  #layouts: 'archives-index'
  permalinks:
    tag: 'blogue/tags/:name/'
    category: 'blogue/categorie/:name/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

