---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: General
- type: jekyll-pages
  label: Pages
  create: all
- type: document
  path: _data/curriculum.yml
  label: Curriculum
- type: heading
  label: Oeuvres
- type: directory
  path: _portfolio
  label: Portfolio
  create: all
  match: "**/*"
  templates:
  - portfolio
- type: document
  path: _data/portfolio-categorie.yml
  label: Catégories
- type: heading
  label: Blogue
- type: jekyll-posts
  label: Articles
  create: all
  templates:
  - post-template
- type: document
  path: _data/blog-categories.yml
  label: Catégories
  new_doc_ext: yml
upload_dir: ''
public_path: https://res.cloudinary.com/npaquet-pastel/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
