---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
collections:
- path: _portfolio
  label: Portfolio
  create: all
- path: _category
  label: Category
  create: all
- path: _posts
  label: Posts
  create: all
  default_front_matter_template: post-template
- path: ''
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
