---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: _portfolio
  label: Portfolio
  create: all
  match: "**/*"
  templates:
  - portfolio
- type: directory
  path: _category
  label: Catégories Blogue
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Articles
  create: all
  templates:
  - post-template
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
